# Generated by Django 3.2.15 on 2023-04-09 10:07

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0039_auto_20230404_1301'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='adress',
            new_name='address',
        ),
        migrations.RemoveField(
            model_name='order',
            name='customer_first_name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='customer_last_name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='customer_phone_number',
        ),
        migrations.AddField(
            model_name='order',
            name='firstname',
            field=models.CharField(default='p', max_length=200, verbose_name='имя клиента'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='lastname',
            field=models.CharField(default='p', max_length=200, verbose_name='фамилия клиента'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='phonenumber',
            field=phonenumber_field.modelfields.PhoneNumberField(default='1', max_length=128, region=None, verbose_name='номер телефона клиента'),
            preserve_default=False,
        ),
    ]
