# Generated by Django 3.2.15 on 2023-05-20 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0046_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new_order', 'Необработанный'), ('cooking', 'Готовится в ресторане'), ('in_delivery', 'Доставляется курьером'), ('compleated', 'Доставлен')], db_index=True, default='new_order', max_length=100, verbose_name='статус заказа'),
        ),
    ]
