# Generated by Django 3.2.15 on 2023-05-20 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0047_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='manager_comment',
            field=models.TextField(blank=True, max_length=300, verbose_name='комментарий'),
        ),
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.TextField(max_length=300, verbose_name='адрес доставки'),
        ),
    ]
