# Generated by Django 3.2.15 on 2023-05-20 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0050_auto_20230520_1410'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('on_site', 'Электронно'), ('cash', 'Наличностью')], db_index=True, default='cash', max_length=100, verbose_name='способ оплаты'),
        ),
    ]
