# Generated by Django 3.2.15 on 2023-05-27 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0051_order_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cooking_restaurant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='foodcartapp.restaurant', verbose_name='готовит ресторан'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('1.new_order', 'Необработанный'), ('2.cooking', 'Готовится в ресторане'), ('3.in_delivery', 'Доставляется курьером'), ('4.compleated', 'Доставлен')], db_index=True, default='1.new_order', max_length=100, verbose_name='статус заказа'),
        ),
    ]
