# Generated by Django 3.2.15 on 2023-06-12 12:53

from django.db import migrations


def fix_mistake_status_completed(apps, schema_editor):
    Order = apps.get_model('foodcartapp', 'Order')
    orders = []
    for order in Order.objects.all().iterator():
        if order.status == '4.compleated':
            order.status = '4.completed'
        orders.append(order)
    Order.objects.bulk_update(orders, ['status'])


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0053_auto_20230527_1910'),
    ]

    operations = [
        migrations.RunPython(fix_mistake_status_completed),
    ]
