# Generated by Django 3.2.15 on 2023-07-15 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0054_auto_20230612_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('1.new_order', 'Необработанный'), ('2.cooking', 'Готовится в ресторане'), ('3.in_delivery', 'Доставляется курьером'), ('4.completed', 'Доставлен')], db_index=True, default='1.new_order', max_length=100, verbose_name='статус заказа'),
        ),
    ]
