# Generated by Django 3.2.15 on 2023-06-03 15:12

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_address', models.CharField(max_length=600, unique=True, verbose_name='адресс')),
                ('coordinates', django.contrib.gis.db.models.fields.PointField(srid=4326, verbose_name='координаты')),
                ('last_update_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='дата запроса к геокодеру')),
            ],
            options={
                'verbose_name': 'Место',
                'verbose_name_plural': 'Места',
            },
        ),
    ]
